coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true
