coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true
codecov:
 token: 8b380c6d-b92d-4bf8-be8d-a7366ce8e5af
