name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.2"
  extras:
    description: "Optional extras to install (comma-separated, e.g., 'docker')"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: 'true'
        cache-suffix: ${{ matrix.python-version }}

    - name: Install Python dependencies (no extras)
      if: ${{ inputs.extras == '' }}
      run: uv sync --frozen --all-packages --python=${{ matrix.python-version }}
      shell: bash

    - name: Install Python dependencies (with extras)
      if: ${{ inputs.extras != '' }}
      run: uv sync --frozen --all-packages --python=${{ matrix.python-version }} --extra ${{ inputs.extras }}
      shell: bash
